// <auto-generated />
using System;
using Bank.CreditCard.Worker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bank.CreditCard.Worker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bank.CreditCard.Worker.Domain.CreditCardEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("card_number");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_date");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("security_code");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("credit_cards", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
