// <auto-generated />
using System;
using Bank.Clients.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bank.Clients.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bank.Clients.Api.Domain.Client", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_date");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("credit_limit");

                    b.Property<string>("Document")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Observation")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observation");

                    b.Property<int>("ProposalStatus")
                        .HasColumnType("int")
                        .HasColumnName("proposal_status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_date");

                    b.HasKey("Id");

                    b.ToTable("clients", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
